org: danielboggiano
app: my-aws-cuentas-api
service: my-aws-cuentas-api

frameworkVersion: "2"

custom:
  version: "v4"
  usersTableName: "users-table-${self:custom.version}-${self:provider.stage}"
  cuentasTableName: "cuentas-table-${self:custom.version}-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CuentasTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    CUENTAS_TABLE: ${self:custom.cuentasTableName}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTableName}
    CuentasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: cuentaId
            AttributeType: S
        KeySchema:
          - AttributeName: cuentaId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.cuentasTableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
